version: "3.9"
services:
  db:
    image: docker.io/postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=application
    volumes:
      - db-data:/var/lib/postgresql/data_chat
    ports:
      - "15432:5432"
    env_file:
      - .env
  app:
    build: .
    user: ${UID:-1000}:${GID:-1000}
    command: [sh, /app/.docker-compose/app.sh]
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:15432/application
      - CACHE_URL=locmemcache://
      - LOG_LEVEL=INFO
      - USERS_SUPERUSER=00000000000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  db-data:
